import { useState } from 'react';
import { Link, useRouterState } from '@tanstack/react-router';
import { Building2, Phone, Mail, LockKeyhole, Menu, X, ExternalLink, ChevronRight, MapPin, Clock, ArrowRight, CalendarDays, Bell } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { announcements, contact, navItems, portals, tagline, type Announcement } from '@/lib/site-data';

export function Brand({ inverse = false }: { inverse?: boolean }) {
  return <Link to="/" className="flex min-w-0 items-center gap-3" aria-label="Gram Panchayat Sonale home">
    <span className={`grid size-12 shrink-0 place-items-center rounded-full border-2 ${inverse ? 'border-footer-accent bg-footer-surface' : 'border-green bg-secondary'}`}><Building2 className={`size-6 ${inverse ? 'text-footer-accent' : 'text-green'}`} /></span>
    <span className="min-w-0 leading-tight"><strong className={`block text-[15px] font-bold sm:text-lg ${inverse ? 'text-footer-foreground' : 'text-primary'}`}>Gram Panchayat Sonale</strong><span className={`block text-sm font-medium ${inverse ? 'text-footer-accent' : 'text-green'}`}>ग्राम पंचायत सोनाळे</span>{!inverse && <small className="block text-[11px] text-muted-foreground">Bhiwandi, Thane, Maharashtra</small>}</span>
  </Link>;
}
export function Header() {
  const [open, setOpen] = useState(false);
  const pathname = useRouterState({ select: s => s.location.pathname });
  return <header className="relative z-50">
    <div className="bg-footer text-footer-foreground"><div className="site-container flex min-h-9 items-center justify-between gap-3 py-1 text-[11px] sm:text-xs"><div className="flex flex-wrap gap-x-5 gap-y-1"><a href="tel:+919890417095" className="inline-flex items-center gap-1.5 hover:text-footer-accent"><Phone className="size-3" />{contact.phone}</a><a href={`mailto:${contact.email}`} className="inline-flex items-center gap-1.5 hover:text-footer-accent"><Mail className="size-3" />{contact.email}</a></div><Link to="/admin/login" className="inline-flex shrink-0 items-center gap-1.5 hover:text-footer-accent"><LockKeyhole className="size-3" />Admin Login</Link></div></div>
    <div className="tricolor" aria-hidden="true" />
    <nav className="border-b border-border bg-card shadow-sm" aria-label="Main navigation"><div className="site-container flex h-[82px] items-center justify-between gap-4"><Brand /><div className="hidden items-center gap-1 lg:flex">{navItems.map(item => <Link key={item.to} to={item.to} className={`rounded px-3 py-2 text-sm font-semibold leading-tight transition-colors ${pathname === item.to ? 'bg-primary text-primary-foreground' : 'text-foreground hover:bg-secondary hover:text-primary'}`}><span className="block">{item.en}</span><span className="mt-0.5 block text-[11px] font-normal opacity-80">{item.mr}</span></Link>)}</div><Button className="lg:hidden" variant="ghost" size="icon" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>
    {open && <div className="site-container border-t border-border bg-card pb-3 lg:hidden">{navItems.map(item => <Link key={item.to} to={item.to} onClick={() => setOpen(false)} className={`flex items-center justify-between border-b border-border px-3 py-3 text-sm ${pathname === item.to ? 'font-bold text-primary' : 'text-foreground'}`}><span>{item.en} <span className="ml-2 text-muted-foreground">{item.mr}</span></span><ChevronRight className="size-4" /></Link>)}</div>}</nav>
  </header>;
}
export function Footer() { return <footer className="bg-footer text-footer-muted"><div className="site-container grid gap-9 py-12 md:grid-cols-2 lg:grid-cols-4"><div><Brand inverse /><p className="mt-5 text-sm leading-7">{tagline}</p></div><div><h3 className="footer-heading">Quick Links</h3><ul className="space-y-2 text-sm">{navItems.map(item => <li key={item.to}><Link to={item.to} className="inline-flex items-center gap-2 hover:text-footer-accent"><ChevronRight className="size-3 text-footer-accent" />{item.en === 'Announcements' ? 'Notices & Announcements' : item.en === 'Feedback' ? 'Submit Feedback' : item.en}</Link></li>)}</ul></div><div><h3 className="footer-heading">Govt. Portals</h3><ul className="space-y-2 text-sm">{portals.map(p => <li key={p.url}><a href={p.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 hover:text-footer-accent"><ExternalLink className="size-3 text-footer-accent" />{p.short}</a></li>)}</ul></div><div><h3 className="footer-heading">Contact</h3><ul className="space-y-3 text-sm leading-6"><li className="flex gap-2"><MapPin className="mt-1 size-4 shrink-0 text-footer-accent" />{contact.address}</li><li><a href="tel:+919890417095" className="flex items-center gap-2 hover:text-footer-accent"><Phone className="size-4 text-footer-accent" />{contact.phone}</a></li><li><a href={`mailto:${contact.email}`} className="flex items-center gap-2 hover:text-footer-accent"><Mail className="size-4 text-footer-accent" />{contact.email}</a></li><li className="flex gap-2"><Clock className="size-4 shrink-0 text-footer-accent" />{contact.hours}</li></ul></div></div><div className="border-t border-footer-line"><div className="site-container flex flex-col justify-between gap-2 py-5 text-xs sm:flex-row"><span>© 2025-26 Group Gram Panchayat Sonale, Bhiwandi, Thane. All rights reserved.</span><span>Designed & Developed By AS SOFTWARE SOLUTION, BHIWANDI | Maharashtra</span></div></div></footer>; }
export function PageHeader({ title, marathi, breadcrumb }: { title: string; marathi: string; breadcrumb: string }) { return <div className="bg-primary text-primary-foreground"><div className="site-container py-10 sm:py-12"><p className="mb-1 text-sm font-medium text-primary-soft">{marathi}</p><h1 className="text-3xl font-bold sm:text-4xl">{title}</h1><nav aria-label="Breadcrumb" className="mt-3 flex items-center gap-1 text-xs text-primary-soft"><Link to="/" className="hover:underline">Home</Link><ChevronRight className="size-3" /><span>{breadcrumb}</span></nav></div></div>; }
export function SectionTitle({ title, marathi, intro }: { title: string; marathi?: string; intro?: string }) { return <div className="mb-7"><div className="mb-3 h-1 w-10 rounded-full bg-green" /><h2 className="text-2xl font-bold text-primary sm:text-[28px]">{title}</h2>{marathi && <p className="mt-1 text-sm font-medium text-green">{marathi}</p>}{intro && <p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">{intro}</p>}</div>; }
export function AnnouncementCard({ item }: { item: Announcement }) { return <article className="flex h-full flex-col rounded-md border border-border bg-card p-5 shadow-sm transition-shadow hover:shadow-md"><div className="mb-4 flex flex-wrap items-center gap-2 text-xs"><span className="inline-flex items-center gap-1 text-muted-foreground"><CalendarDays className="size-3.5" />{item.date}</span><span className="rounded bg-secondary px-2 py-1 font-medium text-green">{item.category}</span></div><h3 className="text-lg font-semibold text-foreground">{item.title}</h3><p className="mt-1 text-sm font-medium text-primary">{item.english}</p><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{item.description}</p><Link to="/announcements" hash={`notice-${item.id}`} className="mt-5 inline-flex w-fit items-center gap-1 text-sm font-semibold text-primary hover:underline">View Details <ArrowRight className="size-4" /></Link></article>; }
export function NoticeIcon() { return <span className="grid size-10 shrink-0 place-items-center rounded-md bg-secondary text-primary"><Bell className="size-5" /></span>; }
export function PrimaryLink({ to, children, outline = false }: { to: '/' | '/about' | '/gallery' | '/announcements' | '/contact' | '/feedback'; children: React.ReactNode; outline?: boolean }) { return <Button asChild variant={outline ? 'outline' : 'default'} size="lg"><Link to={to}>{children}<ArrowRight className="size-4" /></Link></Button>; }
export function routeHead(title: string, description: string) { const name = `${title} | Gram Panchayat Sonale`; return { meta: [{ title: name }, { name: 'description', content: description }, { property: 'og:title', content: name }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }; }
